### ISSUE TITLE
intel drop rate too high

### ISSUE THREAD

**Issue by onedigita** [dixon13/InsurgencyRedux#19]
I am playing right now with some of the guys and the intel drop rate is way to high it seems like 50% or more. otherwise love what youve done.

**\* hef just informed me you turned it down.  i wonder if its 10% per each playe rand its overlapping its def not at 10% its more like 80-90% of the guys going down drop intel

**Comment by dixonbegay** [comment]
hmmm ok. I will look more into the code.

**Comment by dixonbegay** [comment]
Reference this: https://github.com/dixon13/InsurgencyRedux/blob/master/INS/main/functions/fn_intelHandler.sqf#L10

**Comment by dixonbegay** [comment]
Fixed closing
